version: '3.9'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:23.9.1
    environment:
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_USER:
      CLICKHOUSE_PASSWORD:
      CLICKHOUSE_DB:

      APP__DATABASE__CLICKHOUSE_DSN: clickhouse://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@clickhouse:8123/${CLICKHOUSE_DB}
    ports:
      - 8123:8123/tcp
      - 9000:9000/tcp
    ulimits:
      nofile: 262144
    networks:
      - internal
    restart: always
    volumes:
      - clickhouse_data:/var/lib/clickhouse/
  worker:
    image: tps-backend-image:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP__TON_HTTP_API__URL: http://main:8081/api/v2/jsonRPC
      APP__TON_HTTP_API__API_TOKEN:
      APP__COUNTER_ADDRESS:
      APP__RPS:
      APP__DATABASE__CLICKHOUSE_DSN: clickhouse://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@clickhouse:8123/${CLICKHOUSE_DB}
    networks:
      - internal
      - ton-http-api_main
    restart: always
    command: python3 -m backend
  api:
    image: tps-backend-image:latest
    environment:
      APP__TON_HTTP_API__URL: http://main:8081/api/v2/jsonRPC
      APP__TON_HTTP_API__API_TOKEN:
      APP__COUNTER_ADDRESS:
      APP__RPS:
      APP__DATABASE__CLICKHOUSE_DSN: clickhouse://${CLICKHOUSE_USER}:${CLICKHOUSE_PASSWORD}@clickhouse:8123/${CLICKHOUSE_DB}
    networks:
      - internal
    restart: always
    command: uvicorn backend.api.app:app
networks:
  internal:
  ton-http-api_main:
    external: true
volumes:
  clickhouse_data:
